spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/providerdb
    username: appuser
    password: apppassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
  cache:
    type: none
  redis:
    host: redis
    port: 6379 