server:
  port: 8081
  servlet:
    context-path: /api/map

spring:
  application:
    name: map-service
  datasource:
    url: jdbc:postgresql://localhost:5432/providerdb
    username: ${POSTGRES_USER:appuser}
    password: ${POSTGRES_PASSWORD:apppassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
        format_sql: true
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:redispassword}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Custom application properties
app:
  map:
    default-search-radius-km: 5
    max-search-radius-km: 50
    max-results: 100
    cache:
      provider-ttl-seconds: 300
      viewport-ttl-seconds: 120

---
# Docker profile
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/providerdb
  redis:
    host: redis

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/