server:
  port: 8085
  servlet:
    context-path: /api/search

spring:
  application:
    name: search-service
  datasource:
    url: jdbc:postgresql://localhost:5432/providerdb
    username: appuser
    password: apppassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

logging:
  level:
    com.healthcare.searchservice: DEBUG
    org.hibernate.SQL: DEBUG 